# Generated by Django 2.2.2 on 2019-08-18 14:02

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25,
                 verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=25, unique=True,
                 verbose_name='Интернет имя категории(slug)')),
                ('order', models.PositiveSmallIntegerField(
                    default=0, help_text='Установите порядок сортировки от меньшего к большему', verbose_name='Порядок сортитовки')),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    max_length=40, verbose_name='Название товара')),
                ('slug', models.SlugField(max_length=40, unique=True,
                 verbose_name='Интернет имя товара(slug)')),
                ('description', models.TextField(
                    blank=True, verbose_name='Описание товара')),
                ('image', models.ImageField(
                    blank=True, upload_to=store.models.get_product_main_image_path, verbose_name='Основное изображение')),
                ('price', models.DecimalField(decimal_places=2,
                 default=0, max_digits=10, verbose_name='Цена')),
                ('avaible', models.BooleanField(db_index=True,
                 default=True, verbose_name='Товар доступен к продаже')),
                ('new', models.BooleanField(db_index=True,
                 default=False, verbose_name='Новинка')),
                ('added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('image_quantity', models.PositiveSmallIntegerField(
                    default=1, editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='products', to='store.Category', verbose_name='Категория товаров')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['category', 'name'],
                'get_latest_by': ['added'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductExtraImage',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(
                    upload_to=store.models.get_extra_image_path, verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='images', to='store.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение товара',
                'verbose_name_plural': 'Дополнительные изображеия товара',
            },
        ),
    ]
