# Generated by Django 2.2.2 on 2019-08-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopages',
            name='content_text',
            field=models.TextField(
                blank=True, help_text='Данное поле заполняется в HTML разметке', verbose_name='Основной текст страницы'),
        ),
        migrations.AlterField(
            model_name='infopages',
            name='menuname',
            field=models.CharField(
                max_length=30, verbose_name='Имя страницы в нав-меню'),
        ),
        migrations.AlterField(
            model_name='infopages',
            name='slug',
            field=models.SlugField(
                max_length=12, unique=True, verbose_name='интернет имя страницы (slug)'),
        ),
    ]
