# Generated by Django 2.2.2 on 2019-08-27 15:42

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190818_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopageimages',
            name='image',
            field=models.ImageField(upload_to=main.utils.get_infopage_image_path, verbose_name='Изображение'),
        ),
    ]
