"""
Django settings for magaz project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
with open(os.path.join(BASE_DIR, 'magaz/secret_key'), 'r') as fh:
    SECRET_KEY = fh.read().strip()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost', '127.0.0.1']
allowed_host = os.environ.get('ALLOWED_HOST')
if allowed_host:
    ALLOWED_HOSTS += [allowed_host]

SECURE_SSL_REDIRECT = False
SECURE_REDIRECT_EXEMPT = [r'^(?!accounts/profile).*']
# Reverse redirect to http, work only if SECURE_SSL_REDIRECT = True
SECURE_REDIRECT_REVERSE = False


# Application definition

INSTALLED_APPS = [
    'main.apps.MainConfig',
    'customers.apps.CustomersConfig',
    'store.apps.StoreConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap4',
    'django_cleanup',
    'easy_thumbnails',
]

MIDDLEWARE = [
    'main.security.ExtSecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'magaz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processor.main_app',
            ],

        },
    },
]

WSGI_APPLICATION = 'magaz.wsgi.application'

# easy_thumbnails configure

THUMBNAIL_ALIASES = {
    '': {
        'main': {
            'size': (350, 225),
            'crop': 'smart',
        },
        'small': {
            'size': (200, 120),
            'crop': 'scale',
        },
        'vsmall': {
            'size': (150, 90),
            'crop': 'scale',
        },
    },
}

THUMBNAIL_BASEDIR = 'thumbnails'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 6},
    },
]

AUTH_USER_MODEL = 'customers.ExtUser'
LOGOUT_REDIRECT_URL = '/'

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = False
THOUSAND_SEPARATOR = u'\xa0'
NUMBER_GROUPING = 3
USE_THOUSAND_SEPARATOR = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static', 'static_files'),)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Session

SESSION_FILE_PATH = os.path.join(BASE_DIR, '_sessions')
SESSION_CART_NAME = 'cart' #Magaz config

# Default Staff person for staff comments

DEFAULT_USER_ID = 14
