# Generated by Django 2.2.2 on 2019-08-27 14:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('customers', '0002_auto_20190818_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, help_text='Введите 10 цифр телефонного номера без восьмерки,         например 9031234567.', max_length=10, validators=[django.core.validators.RegexValidator(regex='^[\\d]{10}$')], verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, help_text='Введите адрес доставки заказа.', max_length=200, verbose_name='Адрес доставки')),
                ('Комментарий к заказу', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OP', 'Открыт'), ('CF', 'Подтвержден'), ('RD', 'Выполнен'), ('PR', 'Проблема')], db_index=True, default='OP', max_length=2)),
                ('finished', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_cost', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Заказ(общий)',
                'verbose_name_plural': 'Все заказы',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='extuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Введите 10 цифр телефонного номера без восьмерки,         например 9031234567.', max_length=10, validators=[django.core.validators.RegexValidator(regex='^(|[\\d]{10})$')], verbose_name='Номер телефона'),
        ),
        migrations.CreateModel(
            name='SimpleOrder',
            fields=[
                ('baseorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customers.BaseOrder')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(db_index=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Заказ без регистрации',
                'verbose_name_plural': 'Заказы без регистрации',
                'ordering': ['-created'],
            },
            bases=('customers.baseorder',),
        ),
        migrations.CreateModel(
            name='StaffComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('comment', models.TextField(verbose_name='Комментарий:')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffcomments', to='customers.BaseOrder')),
                ('person', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='staffcomments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'default_related_name': 'staffcomments',
            },
        ),
        migrations.CreateModel(
            name='OrderPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('cost', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='customers.BaseOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='store.Product')),
            ],
            options={
                'default_related_name': 'positions',
            },
        ),
        migrations.AddField(
            model_name='baseorder',
            name='products',
            field=models.ManyToManyField(through='customers.OrderPosition', to='store.Product'),
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('baseorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customers.BaseOrder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиентский заказ',
                'verbose_name_plural': 'Клиентские заказы',
                'ordering': ['-created'],
            },
            bases=('customers.baseorder',),
        ),
    ]
