# Generated by Django 2.2.2 on 2019-08-27 15:42

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20190827_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseorder',
            name='slug',
            field=models.SlugField(default=main.utils.get_random_string, max_length=20),
        ),
    ]
