# Generated by Django 2.2.2 on 2019-08-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_baseorder_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseorder',
            name='Комментарий к заказу',
        ),
        migrations.AddField(
            model_name='baseorder',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='simpleorder',
            name='email',
            field=models.EmailField(db_index=True, help_text='На этот адрес будет выслана информация о заказе.', max_length=254, null=True, verbose_name='Адрес эл.почты'),
        ),
        migrations.AlterField(
            model_name='simpleorder',
            name='name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Ваше имя'),
        ),
    ]
