# Generated by Django 2.2.2 on 2019-08-28 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20190827_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcomment',
            name='person',
            field=models.ForeignKey(default=14, editable=False, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='staffcomments', to=settings.AUTH_USER_MODEL),
        ),
    ]
